In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
%matplotlib inline

In [5]:
df_iris = pd.read_csv("./iris.data",header=None)

In [10]:
df_iris.columns = ["sepal_length","sepal_width","petal_length","petal_width","class"]

In [8]:
df = pd.read_csv("./iris.names",sep="\t")

In [9]:
df

                                                                       1. Title: Iris Plants Database
NaN                                                 Updated Sept 21 by C.Blake - Added discrepency...
2. Sources:                                                                                       NaN
     (a) Creator: R.A. Fisher                                                                     NaN
     (b) Donor: Michael Marshall (MARSHALL%PLU@...                                                NaN
     (c) Date: July, 1988                                                                         NaN
3. Past Usage:                                                                                    NaN
   - Publications: too many to mention!!!  Here...                                                NaN
   1. Fisher,R.A. "The use of multiple measurem...                                                NaN
      Annual Eugenics, 7, Part II, 179-188 (193...                                                NaN
      to Mathematical Statistics" (John Wiley, ...                                                NaN
   2. Duda,R.O., & Hart,P.E. (1973) Pattern Cla...                                                NaN
      (Q327.D83) John Wiley & Sons.  ISBN 0-471...                                                NaN
   3. Dasarathy, B.V. (1980) "Nosing Around the...                                                NaN
      Structure and Classification Rule for Rec...                                                NaN
      Environments".  IEEE Transactions on Patt...                                                NaN
      Intelligence, Vol. PAMI-2, No. 1, 67-71.                                                    NaN
      -- Results:                                                                                 NaN
         -- very low misclassification rates (0...                                                NaN
   4. Gates, G.W. (1972) "The Reduced Nearest N...                                                NaN
      Transactions on Information Theory, May 1...                                                NaN
      -- Results:                                                                                 NaN
         -- very low misclassification rates again                                                NaN
   5. See also: 1988 MLC Proceedings, 54-64.  C...                                                NaN
      conceptual clustering system finds 3 clas...                                                NaN
4. Relevant Information:                                                                          NaN
   --- This is perhaps the best known database ...                                                NaN
       recognition literature.  Fisher's paper ...                                                NaN
       and is referenced frequently to this day...                                                NaN
       example.)  The data set contains 3 class...                                                NaN
       where each class refers to a type of iri...                                                NaN
       linearly separable from the other 2; the...                                                NaN
       separable from each other.                                                                 NaN
   --- Predicted attribute: class of iris plant.                                                  NaN
   --- This is an exceedingly simple domain.                                                      NaN
   --- This data differs from the data presente...                                                NaN
NaN                                                 (identified by Steve Chadwick,  spchadwick@esp...
NaN                                                 The 35th sample should be: 4.9,3.1,1.5,0.2,"Ir...
NaN                                                         where the error is in the fourth feature.
NaN                                                    The 38th sample: 4.9,3.6,1.4,0.1,"Iris-setosa"
NaN                                                 where the errors are in the second and third f...
5. Number of Instances: 150 (50 in each of thre...                                                NaN
6. Number of Attributes: 4 numeric, predictive ...                                                NaN
7. Attribute Information:                                                                         NaN
   1. sepal length in cm                                                                          NaN
   2. sepal width in cm                                                                           NaN
   3. petal length in cm                                                                          NaN
   4. petal width in cm                                                                           NaN
   5. class:                                                                                      NaN
      -- Iris Setosa                                                                              NaN
      -- Iris Versicolour                                                                         NaN
      -- Iris Virginica                                                                           NaN
8. Missing Attribute Values: None                                                                 NaN
Summary Statistics:                                                                               NaN
NaN                                                          Min  Max   Mean    SD   Class Correla...
   sepal length: 4.3  7.9   5.84  0.83    0.782...                                                NaN
    sepal width: 2.0  4.4   3.05  0.43   -0.4194                                                  NaN
   petal length: 1.0  6.9   3.76  1.76    0.949...                                                NaN
    petal width: 0.1  2.5   1.20  0.76    0.956...                                                NaN
9. Class Distribution: 33.3% for each of 3 clas...                                                NaN